/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=dist/server/wrangler.json --include-runtime=false --strict-vars=false --env-interface=TfcWebEnv worker/cloudflare-env.d.ts` (hash: 531f31d9eeb84a53dd289e087f3eeb40)
interface __BaseEnv_TfcWebEnv {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../dist/server/index");
	}
	interface Env extends __BaseEnv_TfcWebEnv {}
}
interface TfcWebEnv extends __BaseEnv_TfcWebEnv {}
